ganagro/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('ganagroapp.urls')),

]

ganagroapp/urls.py
from django.conf.urls import include, url
from . import views
from django.contrib.auth.views import login
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.views import logout
from django.conf.urls.static import static
from django.conf import settings
app_name = 'ganagroapp'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^product/(?P<pk>[0-9]+)/$', views.product_detail, name='product_detail'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.product_category, name='product_category'),
    url(r'^product/new/$', views.new_product, name='new_product'),

    url(r'^login/$',login,{'template_name':'login.html'}, name='login'),
    url(r'^logout/$',logout,{'template_name':'index.html'},name='logout'),
    url(r'^profile/(?P<pk>[0-9]+)/$', views.profile, name='profile'),
    url(r'^profile/(?P<pk1>[0-9]+)/product/(?P<pk>[0-9]+)/edit/$', views.edit_product, name='edit_product'),
    url(r'^new_user/$', views.register_user, name='new_user'),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ganagroapp/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from PIL import Image as img
class Client(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    ci = models.CharField(max_length=9)
    birth_date = models.DateField(null=True, blank=True)
    phone = models.CharField(max_length=20)
    city = models.CharField(max_length=20, default='')
    def __str__(self):
        return self.ci
        return self.phone
        return self.city


class Product(models.Model):
    client = models.ForeignKey('Client')
    category = models.ForeignKey('Category')
    product = models.CharField(max_length=30)
    price = models.PositiveIntegerField(default=100)
    location = models.CharField(max_length=100,default='trinidad')
    description = models.CharField(max_length=100)
    created_date = models.DateTimeField(default=timezone.now)
    def __str__(self):
            return self.product
            return self.description
            return str(self.created_date)

class Image(models.Model):
    product = models.ForeignKey('Product')
    image = models.ImageField(upload_to='products')
    image_height = models.PositiveIntegerField(null=True, blank=True, editable=False )
    image_width = models.PositiveIntegerField(null=True, blank=True, editable=False)

    def __unicode__(self):
        return "{0}".format(self.image)

    def save(self):
        if not self.image:
            return

        super(Image, self).save()

        image = img.open(self.image)
        (width, height) = image.size
        size = ( 500, 300)
        image = image.resize(size)
        image.save(self.image.path)


class Category(models.Model):
    name=models.CharField(max_length=30)
    def __str__(self):
        return self.name

class Token(models.Model):
    token=models.TextField()
    def __str__(self):
        return self.token
# Create your models here.

ganagroapp/forms.py
from django import forms
from .models import Product, Image, Client,Token
from django.forms.extras.widgets import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class TokenForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(TokenForm, self).__init__(*args, **kwargs)
        self.fields['token'].widget.attrs = {'class' : 'form-control', 'required': 'required', 'placeholder': 'Inserte codigo '}
    class Meta:
        model = Token
        fields =['token']

class ProductForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        self.fields['product'].widget.attrs = {'class' : 'form-control', 'required': 'required', 'placeholder': 'Titulo del anuncio'}
        self.fields['description'].widget.attrs = {'class' : 'form-control', 'required': 'required', 'placeholder': 'Descripcion del anuncio'}
        self.fields['category'].widget.attrs = {'class' : 'form-control', 'required': 'required'}
    class Meta:
        model = Product
        fields = ('product','description','category')

class ProductImageForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProductImageForm, self).__init__(*args, **kwargs)
        self.fields['image'].widget.attrs = {'class' : 'form-control', 'required': 'required'}
    class Meta:
        model = Image
        fields = ['image']

class ClientForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ClientForm, self).__init__(*args, **kwargs)
        self.fields['ci'].widget.attrs = {'class' : 'form-control', 'required': 'required' }
        self.fields['birth_date'].widget.attrs = {'class' : 'form-control', 'required': 'required', 'placeholder': ' mm-dd-yyy'}
        self.fields['phone'].widget.attrs = {'class' : 'form-control', 'required': 'required'}
        self.fields['city'].widget.attrs = {'class' : 'form-control', 'required': 'required'}
    class Meta:
        model = Client
        fields = ['ci','birth_date','phone','city']

class UserCreateForm(UserCreationForm):
    email = forms.EmailField(required=True)
    class Meta:
        model = User
        fields = {"username","email","first_name","last_name"}
        def clean_email(self):
            email = self.cleaned_data['email']
            if User.objects.filter(email=email).exists():
                raise ValidationError("Email already exists")
            return email
        def clean(self):
            form_data = self.cleaned_data
            if form_data['password'] != form_data['password']:
                self._errors["password"] = "password do not match"
                del form_data["password"]
            return form_data


    def __init__(self, *args, **kwargs):
        super(UserCreateForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class' : 'form-control', 'required': 'required'})
        self.fields['email'].widget.attrs.update({'class' : 'form-control', 'required': 'required'})
        self.fields['first_name'].widget.attrs.update({'class' : 'form-control', 'required': 'required'})
        self.fields['last_name'].widget.attrs.update({'class' : 'form-control', 'required': 'required'})
        self.fields['password1'].widget.attrs.update({'class' : 'form-control', 'required': 'required'})
        self.fields['password2'].widget.attrs.update({'class' : 'form-control', 'required': 'required'})

ganagroapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Product,Client,Image,Token
from django.utils import timezone
from .forms import *
from django.template import RequestContext, loader, Context, Template
from django.core.urlresolvers import reverse
from django.http import *
from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):
    images = Image.objects.select_related()
    category = Category.objects.select_related()
    products = Product.objects.order_by('-created_date').select_related()
    return render(request,'ganagroapp/index.html', {'category' : category, 'products' : products, 'images': images} )

def product_detail(request, pk):
    product = get_object_or_404(Image, product_id=pk)
    images = Image.objects.select_related()
    category = Category.objects.select_related()
    return render(request,'ganagroapp/product_detail.html',{'category' : category, 'product': product, 'images': images} )

def product_category(request, pk):
    images = Image.objects.select_related()
    products =Product.objects.filter(category=pk).order_by('-created_date').select_related
    category = Category.objects.select_related()
    return render(request,'ganagroapp/product_category.html',{'category' : category, 'products' : products, 'images' : images})

@login_required
def profile(request, pk):
    images = Image.objects.select_related()
    #client = Client.objects.filter(user_id=pk).select_related()
    products = Product.objects.filter(client_id=pk).order_by('-created_date').select_related
    category = Category.objects.select_related()
    return render(request,'ganagroapp/profile.html',{'category' : category, 'products' : products, 'images' : images})

def register_user(request):
    category = Category.objects.select_related()
    username = password = email = first_name = last_name=''
    if request.method == "POST":
        form = ClientForm(request.POST)
        user_form = UserCreateForm(request.POST)
        if user_form.is_valid() and form.is_valid():
            client = form.save(commit=False)
            usuario = User(username=request.POST['username'], email=request.POST['email'], first_name=request.POST['first_name'], last_name=request.POST['last_name'])
            usuario.set_password(request.POST['password1'])
            usuario.save()
            usuario.refresh_from_db()
            client.user_id = usuario.pk
            client.save()
            return HttpResponseRedirect(reverse('ganagroapp:index'))
    else:
        user_form = UserCreateForm()
        form = ClientForm()
    dictionary = {
		'user_form': user_form,
		'page_title': 'Aplicacion - Register',
		'body_class': 'register',
	}
    return render(request, "new_user.html",{'user_form' : user_form, 'form' : form, 'category': category })
@login_required
def new_product(request):
    category = Category.objects.select_related()
    client = get_object_or_404(Client, user=request.user.pk)
    if request.method == "POST":


            try :
                form = ProductForm(request.POST)
                form2 = ProductImageForm(request.POST, request.FILES)
                token = TokenForm(request.POST)
                tokens = Token.objects.get(token = request.POST['token'])
                if tokens.token == request.POST['token'] :
                    if form.is_valid() and form2.is_valid() and token.is_valid():

                        product = form.save(commit=False)
                        image = form2.save(commit=False)
                        product.client_id = client.pk
                        product.created_date = timezone.now()
                        product.save()
                        image.product_id = product.pk
                        image.save()
                        message ="Producto cargado exitosamente"
                        return redirect('ganagroapp:product_detail', pk=product.pk)
            except Exception:
                message="codigo invalido"

    else:
        form = ProductForm()
        form2 = ProductImageForm()
        token = TokenForm()
        message=""
    return render(request, 'ganagroapp/new_product.html',{'form': form, 'form2':form2, 'token':token,'category': category, 'message':message})

@login_required
def edit_product(request, pk, pk1):
    category = Category.objects.select_related()
    product = get_object_or_404(Product, pk=pk)
    if request.method == "POST":
        form = ProductForm(request.POST,instance=product)
        if form.is_valid():
            product = form.save(commit=False)
            product.save()
            return redirect('ganagroapp:profile',pk=pk1)
    else:
        form = ProductForm(instance=product)
    return render(request, 'ganagroapp/new_product.html',{'form': form, 'category':category})

ganagroapp/templates/ganagroapp/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
        <head>
            <title>Agronet</title>
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <link rel="stylesheet" href="{% static 'css/style.css' %}" >
            <link href="https://fonts.googleapis.com/css?family=Montserrat:200,300,400,700,900" rel="stylesheet">
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        </head>
        <body>


                    <nav class="navbar navbar-inverse">

                        <div class="container-fluid">

                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                                <a href="{% url 'ganagroapp:index' %}" class="navbar-brand ">AgroNet</a>
                            </div>

                        <div class="collapse navbar-collapse" id="myNavbar">
                            <!-- Navbar content -->
                            <ul class="nav navbar-nav">

                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">CATEGORIAS <span class="caret"></span> </a>

                                        <ul class="dropdown-menu">
                                            {% for cat in category %}
                                                <li><a href="{% url 'ganagroapp:product_category' pk=cat.pk %} ">{{ cat.name }}</a></li>
                                            {% endfor %}
                                        </ul>
                                </li>


                 {% if user.is_authenticated %}


                     <li class="dropdown" >
                          <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">PERFIL <span class="caret"></span> </a>
                          <ul class="dropdown-menu">

                              <li ><a href="{% url 'ganagroapp:logout' %}">Cerrar sesion <span class="glyphicon glyphicon-log-out"></span></a></li>
                              <li ><a href="{% url 'ganagroapp:profile' pk=user.pk %}">{{ user.first_name }} <span class="glyphicon glyphicon-user"></a></li>
                              <li> <a href="{% url 'ganagroapp:new_product' %}" >Crear Anuncio</a> </li>

                          </ul>

                     </li>






                {% else %}


                      <li class="active" >
                        <a href="{% url 'ganagroapp:login' %}" >iniciar session <span class="glyphicon glyphicon-log-in"></span></a></a>
                      </li>


                {% endif %}
                    </ul>
                    <form class="navbar-form navbar-left">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Search">
                        </div>
                        <button type="submit" class="btn btn-default">buscar</button>
                    </form>
                </div>
            </div>
        </nav>

        <main>
            <section class="container">
            {% block content %}

            {% endblock content %}
            </section>
            <footer></footer>
        </main>
        </body>
    </html>

ganagroapp/templates/ganagroapp/index.html
{% extends 'ganagroapp/base.html' %}

{% load staticfiles %}





{% block content %}

<!-- all products-->

<div class="container-fluid">
    {% for product in products %}
        {% for image in images %}
            {% if image.product.pk == product.pk %}

            <div class="row panel panel-default">
                <div class="panel-body ">
                <div class=" col-xs-7 col-sm-4 col-md-4 col-lg-3" >
                    <img src="  {{ image.image.url }} " class="img-responsive img-rounded img-size">
                </div>
                <div class="col-xs-5 col-sm-8 col-md-8 col-lg-9">

                        <h3>  <a href="{% url 'ganagroapp:product_detail' pk=product.pk %}">{{ product.product }}</a> </h3>
                        <p class="text-justify"> {{ product.description }} </p>
                        <p> <b>BS {{ product.price }} </b></p>


                </div>
            </div>
            </div>

            {% endif %}
        {% endfor %}
    {% endfor %}

    </div>


{% endblock content %}

ganagroapp/templates/ganagroapp/login.html
{% extends 'ganagroapp/base.html' %}
{% load staticfiles %}

{% block content %}
    <form  method="post">
        {% csrf_token %}
        <div class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
            <input id="username" type="text" class="form-control" name="username" placeholder="usuario">

        </div>
        <div class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
            <input id="password" type="password" class="form-control" name="password" placeholder="Password">
        </div>
        <div class="row">
            <a href="#">olvide mi contrasenha </a>
            <button class="btn btn-lg btn-success btn-block" type="submit" name="login"/>Login</button>
        </div>
    </form>
    <a href="{% url 'ganagroapp:new_user' %}">Crear nueva Cuenta </a>
{% endblock %}

ganagroapp/templates/ganagroapp/new_product.html
{% extends 'ganagroapp/base.html' %}
{% load staticfiles %}


{% block content %}
<div class="row panel panel-success">
    <div class="panel-heading  text-center"> <h3> Crear Anuncio </h3> </div>
    <div class="panel-body">
    <form method="POST" enctype="multipart/form-data" class="product-form">{% csrf_token %}
    <div class="form-group row">
     <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
     </div>
     <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
        {{ form.non_field_errors }}
        <div class="input-group input-group-sm col-xs-6">
            {{ form.subject.errors }}
            <label for="{{ token.token.id_for_label }}">Codigo:</label>
            {{ token.token }}
        </div>
        <div class="input-group input-group-sm col-xs-6">
            {{ form.subject.errors }}
            <p>{{ message }}<p>
            <label for="{{ form.product.id_for_label }}">Nombre del producto: </label>
            {{ form.product }}
        </div>
        <div class="input-group input-group-sm col-xs-6">
            <label for="{{ form.description.id_for_label }}">Descripcion del producto: </label>
            {{ form.description }}
        </div>
        <div class="input-group input-group-sm col-xs-6">
            <label for="{{ form.category.id_for_label }}">Seleccione una categoria: </label>
            {{ form.category }}

        </div>
        <div class="input-group input-group-sm col-xs-6">
            <label for="{{ form2.Image.id_for_label }}">Seleccione una imagen: </label>
            {{ form2.image }}
        </div>
        <div class="input-group input-group-sm col-xs-6">
        <button type="submit" class="btn btn-lg btn-success btn-block">Guardar</button>
        </div>
    </div>
    </div>
    </form>
</div>
{% endblock %}

ganagroapp/templates/ganagroapp/new_user.html
{% extends 'ganagroapp/base.html' %}
{% load staticfiles %}






{% block content %}
<div class="row panel panel-success">
    <div class="panel-heading  text-center"> <h3> Resgistrate como usuario </h3> </div>
    <div class="panel-body">
<form method="post">
    <div class="form-group row">
     <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
     </div>
     <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
    {% csrf_token %}
    {{ user_form.non_field_errors }}
    {% csrf_token %}
    {{ form.non_field_errors }}

    <div class="input-group input-group-sm col-xs-6">
        {{ user_form.subject.errors }}
        <label for="{{ user_form.username.id_for_label }}">Nombre de usuario </label>
        {{ user_form.username }}
    </div>
    <div class="input-group input-group-sm col-xs-6">
        <label for="{{ user_form.email.id_for_label }}">Email </label>
        {{ user_form.email}}
    </div>
    <div class="input-group input-group-sm col-xs-6">
        <label for="{{ user_form.first_name.id_for_label }}">Nombre </label>
        {{ user_form.first_name }}

    </div>
    <div class="input-group input-group-sm col-xs-6">
        <label for="{{ user_form.last_name.id_for_label }}">Apellido </label>
        {{ user_form.last_name }}
    </div>
    <div class="input-group input-group-sm col-xs-6">
        <label for="{{ form.ci.id_for_label }}">carnet de identidad </label>
        {{ form.ci }}
    </div>
    <div class="input-group input-group-sm col-xs-6">
        <label for="{{form.birth_date.id_for_label }}">Fecha de nacimiento </label>
        {{ form.birth_date }}
    </div>
    <div class="input-group input-group-sm col-xs-6">
        <label for="{{ form.phone.id_for_label }}">Telefono </label>
        {{ form.phone }}
    </div>
    <div class="input-group input-group-sm col-xs-6">
        <label for="{{ form.city.id_for_label }}">ciudad </label>
        {{ form.city }}
    </div>
    <div class="input-group input-group-sm col-xs-6">
        <label for="{{ user_form.password1.id_for_label }}">Contrasenha </label>
        {{ user_form.password1 }}
    </div>
    <div class="input-group input-group-sm col-xs-6">
        <label for="{{ user_form.password2s.id_for_label }}">repita la contrasenha </label>
        {{ user_form.password2 }}
    </div>
    <div class="input-group input-group-sm col-xs-6">


    <p><input type="submit" value="Registrar"  class="btn btn-lg btn-success btn-block" /> </p>
    </div>
</div>
</div>
</form>
</div>
</div>


{% endblock content %}

ganagroapp/templates/ganagroapp/product_category.html
{% extends 'ganagroapp/base.html' %}
{% load staticfiles %}




{% block content %}

    <!-- all products-->

<div class="container-fluid">
    {% for product in products %}
        {% for image in images %}
            {% if image.product.pk == product.pk %}

            <div class="row panel panel-default">
                <div class="panel-body">
                <div class=" col-xs-7 col-sm-4 col-md-4 col-lg-3" >
                    <img src="  {{ image.image.url }} " class="img-responsive img-rounded">
                </div>
                <div class="col-xs-5 col-sm-8 col-md-8 col-lg-9">

                        <h3>   <a href="{% url 'ganagroapp:product_detail' pk=product.pk %}">{{ product.product }}</a> </h3>
                        <p> {{ product.description }} </p>

                </div>
            </div>
            </div>

            {% endif %}
        {% endfor %}
    {% endfor %}
</div>

{% endblock content %}

ganagroapp/templates/ganagroapp/product_detail.html
{% extends 'ganagroapp/base.html' %}
{% load staticfiles %}


{% block content %}

<!-- all products-->
<div class="container-fluid">
<div class="row panel panel-default">
    <div class="panel-body">
        <div class=" col-xs-7 col-sm-4 col-md-4 col-lg-3" >
            <img src="  {{ product.image.url }} " class="img-responsive img-rounded">
        </div>
        <div class="col-xs-5 col-sm-8 col-md-8 col-lg-9">

                <h3>  {{ product.product.client.user.first_name }} {{ product.product.client.user.last_name }} </h3>
                <h3>   {{ product.product }} </h3>
                <p> {{ product.product.description }} </p>
                <h3> {{ product.product.client.phone }} </h3>

        </div>
    </div>
</div>
</div>
{% endblock content %}

ganagroapp/templates/ganagroapp/profile.html
{% extends 'ganagroapp/base.html' %}
{% load staticfiles %}

{% block content %}
<div class="container-fluid">
<!-- all products-->
<h1> Mis ofertas </h1>

{% for product in products %}
    {% for image in images %}
        {% if image.product.pk == product.pk %}
        <div class="row panel panel-default">
            <div class="panel-body">
            <div class=" col-xs-7 col-sm-4 col-md-4 col-lg-3">
                <img src="  {{ image.image.url }} " class="img-responsive img-rounded">
            </div>
            <div class="col-xs-5 col-sm-8 col-md-8 col-lg-9">

                    <a class="btn btn-default" href="{% url 'ganagroapp:edit_product' pk=product.pk pk1=user.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
                    <h3> <a href="{% url 'ganagroapp:product_detail' pk=product.pk %}">{{ product.product }}</a> </h3>
                    <p> DESCRIPCION:  {{ product.description }} </p>

            </div>
        </div>
        </div>
        {% endif %}
    {% endfor %}
{% endfor %}

</div>






{% endblock content %}